### ISSUE TITLE
parser_wrapper.py?

### ISSUE THREAD

**Issue by scottlyden** [PatentsView/PatentsView-DB#97]
Hi.  The wiki suggests that parser_wrapper.py is pretty key to running the code.  I just cloned the repo, and I think this file is missing.  Has the method of running the code changed?  Any guidance for running the code on recent bulk data files would be greatly appreciated. Thanks.

**Comment by emelluso** [comment]
@DiPietroch We fixed this by updating the readme file, right? Ready to close?
